### ISSUE TITLE
how to get rank according to private contributions ?

### ISSUE THREAD

**Issue by Dastnbek** [filiptronicek/commits-top-api#5]

**Comment by filiptronicek** [comment]
Not possible ATM, but I'll tackle it later today. @Dastnbek

**Comment by filiptronicek** [comment]
OK, I realized it is quite possible, just use the `private_users` key. @Dastnbek 
![json](https://user-images.githubusercontent.com/29888641/87452527-98db5780-c601-11ea-9eae-ae1f16aa164c.png)
